trigger:
  branches:
    include:
      - master

pr:
  branches:
    include:
      - master

pool:
  vmImage: 'macos-latest'

steps:
  # Passo 1: Clona o repositório do Flutter
  - script: |
      echo "Clonando Flutter na branch estável..."
      git clone https://github.com/flutter/flutter.git -b stable --depth 1
    displayName: 'Clonar Flutter'

  # Passo 2: Adiciona Flutter ao PATH para os próximos comandos
  - script: |
      echo "Configurando PATH do Flutter..."
      echo "##vso[task.prependpath]$(System.DefaultWorkingDirectory)/flutter/bin"
    displayName: 'Configurar PATH do Flutter'

  # Passo 3: Limpar o cache do Flutter e instalar as dependências do projeto
  - script: |
      echo "Limpando o cache do Flutter..."
      flutter clean

      echo "Instalando dependências..."
      flutter pub get
    displayName: 'Limpar cache e obter dependências'

  # Passo 4: Verificar a formatação do código
  - script: |
      echo "Verificando formatação do código..."
      dart format --output=none .
    displayName: 'Verificar formatação do código'

  # Passo 5: Analisar o código (ignorando avisos)
  - script: |
      echo "Analisando o código fonte (ignorando avisos)..."
      flutter analyze --no-fatal-warnings
    displayName: 'Analisar código'

  # Passo 6: Executar testes unitários
  - script: |
      echo "Executando testes unitários..."
      flutter test
    displayName: 'Executar testes unitários'

  # Passo 7: Compilar o appbundle para Android
  - script: |
      echo "Compilando appbundle Android..."
      flutter build appbundle
    displayName: 'Compilar appbundle Android'