trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: 'macos-latest'

steps:
  - script: |
      # Clona o repositório do Flutter na versão estável
      echo "Clonando Flutter..."
      git clone https://github.com/flutter/flutter.git -b stable --depth 1

      # Adiciona o Flutter ao PATH para os próximos comandos funcionarem
      echo "Adicionando Flutter ao PATH..."
      export PATH="$PWD/flutter/bin:$PATH"

      # Verifica a versão do Flutter instalada
      echo "Verificando versão do Flutter..."
      flutter --version

      # Instala as dependências do projeto definidas no pubspec.yaml
      echo "Instalando dependências..."
      flutter pub get

      # Verifica a formatação do código Dart
      echo "Verificando formatação do código..."
      dart format --output=none .

      # Realiza análise estática no código
      echo "Analisando o código do projeto..."
      flutter analyze

      # Executa os testes automatizados
      echo "Executando testes..."
      flutter test

      # Gera o appbundle para Android
      echo "Gerando appbundle..."
      flutter build appbundle
    displayName: 'Configurar Flutter e Executar Pipeline'
