trigger:
  branches:
    include:
      - master

pr:
  branches:
    include:
      - master

pool:
  vmImage: 'macos-latest'

variables:
  FLUTTER_HOME: '$(Pipeline.Workspace)/flutter'

steps:
  # Passo 1: Clonar o Flutter
  - script: |
      echo "Clonando Flutter estável..."
      git clone https://github.com/flutter/flutter.git -b stable --depth 1 $(FLUTTER_HOME)
    displayName: 'Clonar Flutter'

  # Passo 2: Adicionar Flutter ao PATH globalmente
  - script: |
      echo "Adicionando Flutter ao PATH..."
      echo "##vso[task.prependpath]$(FLUTTER_HOME)/bin"
    displayName: 'Configurar PATH do Flutter'

  # Passo 3: Instalar dependências
  - script: |
      flutter pub get
    displayName: 'Instalar dependências'

  # Passo 4: Verificar formatação do código
  - script: |
      dart format --output=none . || true
    displayName: 'Verificar formatação'

  # Passo 5: Analisar o código
  - script: |
      flutter analyze --no-fatal-warnings || true
    displayName: 'Analisar código'

  # Passo 6: Executar testes
  - script: |
      flutter test
    displayName: 'Executar testes'

  # Passo 7: Gerar appbundle
  - script: |
      flutter build appbundle
    displayName: 'Gerar appbundle'
