trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: 'macos-latest'

steps:
  # Passo 1: Clona o repositório do Flutter
  - script: |
      echo "Clonando Flutter na branch estável..."
      git clone https://github.com/flutter/flutter.git -b stable --depth 1
    displayName: 'Clonar Flutter'

  # Passo 2: Adiciona Flutter ao PATH para os próximos comandos
  - script: |
      echo "Configurando PATH do Flutter..."
      echo "##vso[task.prependpath]$(System.DefaultWorkingDirectory)/flutter/bin"
    displayName: 'Configurar PATH do Flutter'

  # Passo 3: Verifica instalação e obtém dependências do projeto
  - script: |
      flutter --version
      flutter pub get
    displayName: 'Verificar Flutter e instalar dependências'

  # Passo 4: Verifica a formatação e analisa o código
  - script: |
      echo "Verificando formatação do código..."
      dart format --output=none .

      echo "Analisando o código fonte..."
      flutter analyze
    displayName: 'Formatar e analisar código'

  # Passo 5: Executa os testes e gera o appbundle
  - script: |
      echo "Executando testes unitários..."
      flutter test

      echo "Compilando appbundle Android..."
      flutter build appbundle
    displayName: 'Testar e compilar app'
